# Generated by Django 5.2.5 on 2025-11-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('PayTM', 'PayTM'), ('Credit Card', 'Credit Card')], max_length=100)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.student')),
            ],
        ),
    ]
